[package]
name = "iotex-ws-lock"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.5.3", features = ["full", "getrandom"] }
async-channel = "2.3.1"
num_cpus = "1.16.0"
rand = "0.8.5"
tokio = { version = "1.41.0", features = ["full"] }
